"""empty message

Revision ID: 108544904105
Revises: 48613225d8db
Create Date: 2024-06-24 19:36:33.429421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108544904105'
down_revision = '48613225d8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_list', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
