"""empty message

Revision ID: 48613225d8db
Revises: fa3d319beb35
Create Date: 2024-06-23 21:03:55.497615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48613225d8db'
down_revision = 'fa3d319beb35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('open_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('session_key', sa.VARCHAR(length=128), nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=128), nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('open_id')
    )
    # ### end Alembic commands ###
