"""empty message

Revision ID: fa3d319beb35
Revises: b5631f3f9b32
Create Date: 2024-06-20 22:59:39.166442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3d319beb35'
down_revision = 'b5631f3f9b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_list', schema=None) as batch_op:
        batch_op.drop_column('upload_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_time', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
